overview:
  enabled: true
  text: This is going to be the overview text
compositionstatus:
  enabled: true
applicationstatus:
  enabled: true
terminal:
  enabled: true
events:
  enabled: true
yamlviewer:
  enabled: true
namespace: krateo-system
global:
  compositionId: compositionId
  compositionApiVersion: compositionApiVersion
  compositionResource: compositionResource