name: release-tag

on:
  push:
    tags: ["[0-9]+.[0-9]+.[0-9]+"]

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract Version
        id: tagger
        uses: battila7/get-version-action@v2

      - name: Print Version
        run: |
          echo ${{steps.tagger.outputs.version}}
          echo ${{steps.tagger.outputs.version-without-v}}

      - name: Replace Version in Chart.yaml
        run: sed -i 's/CHART_VERSION/${{ steps.tagger.outputs.version-without-v }}/g' ./chart/Chart.yaml

      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.HELM_CHARTS_BOT }}
          charts_dir: ./
          charts_url: https://charts.krateo.io
          owner: krateoplatformops
          repository: helm-charts
          branch: gh-pages
